version: 2

jobs:
  deploy_to_eks:
    docker:
      - image: cimg/aws:2023.08
    steps:
      - checkout
      - run:
          name: AWS CLI Command
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_session_token $AWS_SESSION_TOKEN
            aws s3 ls  # Thực hiện các lệnh AWS CLI tại đây
      - run:
          name: Authenticate with EKS and Docker Hub
          command: |
            aws eks update-kubeconfig --name MyEKSCluster1 --region us-east-1
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Apply k8s manifests
          command: |
            kubectl apply -f k8s-manifests/backend-deployment.yaml
            kubectl apply -f k8s-manifests/backend-service.yaml
            kubectl expose deployment backend-deployment --type=LoadBalancer --name=publicbackend
            kubectl get pods
            kubectl get services

  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_eks:
          requires:
            - build
          context:
            - aws-secrets
            - docker-secrets