apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: trunglam12/udacitylabdevopsfinal:latest
          ports:
            - containerPort: 80
    
