apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  containers:
    - name: flask-container
      image: trunglam12/udacitylabdevopsfinal:latest
      ports:
        - containerPort: 80